import Head from 'next/head'
import Image from 'next/image'
import React from "react";

import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [inputValue, setInputValue] = React.useState('')
  const [outputValue, setOutputValue] = React.useState('')

  const handleSubmit = async (event) => {
    event.preventDefault()

    // Make the API call here using the inputValue
    const response = await fetch(`https://api.openai.com/v1/engines/davinci/jobs`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${process.env.OPENAI_API_KEY}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        prompt: inputValue,
        max_tokens: 100
      })
    })

    const data = await response.json()
    setOutputValue(data.choices[0].text)
    setInputValue('')
  }


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Sugomi</h1>
        <p>
          A language model powered by OpenAI
        </p>
        <p>
          Ask me anything!
        </p>
        <form onSubmit={handleSubmit}>
          <input
            type="text"
            value={inputValue}
            onChange={(event) => setInputValue(event.target.value)}
            placeholder="Type your question here..."
          />
          <button type="submit">
            Submit
          </button>
        </form>
        {outputValue && (
          <div>
            <hr />
            <p>
              {outputValue}
            </p>
          </div>
        )}
        
      </main>

      <style jsx>{`
        main {
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          height: 100vh;
        }
        h1 {
          font-size: 48px;
          margin-bottom: 16px;
        }
        p {
          font-size: 24px;
        }
        form {
          display: flex;
          flex-direction: column;
          align-items: center;
        }
        input[type='text'] {
          width: 50%;
          padding: 16px;
          font-size: 18px;
          margin-bottom: 16px;
        }
        button[type='submit'] {
          width: 50%;
          padding: 16px;
          font-size: 18px;
        }
      `}
      </style>

    </>
  )
}
